### ISSUE TITLE
Who's way of using is correct? Koalas? Yours? Both?

### ISSUE THREAD

**Issue by Joshua-Ronan-Phillips** [fcscripters/react-final-countdown#9]
Koalas way of how to use:

``` JavaScript
var React         = require('react');
var ReactDOM      = require('react-dom');
var PointerTools  = require('react-mouse-pointer-tools');
var rootElement   = document.body.getElementById("wrapper");

ReactDOM.render(
  <PointerTools color="pink" showRulers={true} />,
  rootElement
);
```

your way:

``` Javascript
After installation add the following to your main js file i.e. app.js

var Countdown = require('react-the-final-countdown');
And add the Countdown component where you are returning your HTML:

<Countdown min = {3} msg ="Close the bloody fridge" afterUnmount = {this.afterUnmount}/>

```

I can't work out which way is correct or if they both are?

**Comment by sohilpandya** [comment]
I think the way we are instructing users means that if they already have an app setup, then all they need to do is add the `<Countdown min = {3} msg ="Close the bloody fridge" afterUnmount = {this.afterUnmount}/>` in there app so we are not rendering the component itself in the app.js.

Basically, webpack is not the only way to run react, you can use Browserify and others, this means that Koala method is specific to the webpack way of running, where as ours means we just add it to the app.js and don't really care about how they have setup react, could be any of the above and it should still work.

**Comment by Joshua-Ronan-Phillips** [comment]
Thanks
